controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
commentaire_add:
  path: /commentaire/add/{recetteId}
  controller: App\Controller\CommentaireController::addCommentaire
  methods: POST

commentaire_delete:
  path: /commentaire/delete/{id}
  controller: App\Controller\CommentaireController::deleteCommentaire
  methods: POST
