<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB0qqAxB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB0qqAxB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB0qqAxB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB0qqAxB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB0qqAxB\App_KernelDevDebugContainer([
    'container.build_hash' => 'B0qqAxB',
    'container.build_id' => '1100faf1',
    'container.build_time' => 1734004244,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB0qqAxB');
