<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxcDpYF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxcDpYF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxcDpYF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxcDpYF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxcDpYF\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxcDpYF',
    'container.build_id' => 'b7869c77',
    'container.build_time' => 1732116539,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxcDpYF');
