<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEod6tUx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEod6tUx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEod6tUx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEod6tUx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEod6tUx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Eod6tUx',
    'container.build_id' => 'cedbe5c1',
    'container.build_time' => 1734124188,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEod6tUx');
