<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_ingredient_nouvelle' => [[], ['_controller' => 'App\\Controller\\IngredientController::nouvelleIngredient'], [], [['text', '/creation/ingredient']], [], [], []],
    'app_ingredient_show' => [['id'], ['_controller' => 'App\\Controller\\IngredientController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ingredient']], [], [], []],
    'app_ingredients_list' => [[], ['_controller' => 'App\\Controller\\IngredientController::listIngredients'], [], [['text', '/ingredients']], [], [], []],
    'ingredient_delete' => [['id'], ['_controller' => 'App\\Controller\\IngredientController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ingredient']], [], [], []],
    'app_recette_create' => [[], ['_controller' => 'App\\Controller\\RecetteController::create'], [], [['text', '/recette/nouvelle']], [], [], []],
    'recette_show' => [['id'], ['_controller' => 'App\\Controller\\RecetteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/recette']], [], [], []],
    'recette_delete' => [['id'], ['_controller' => 'App\\Controller\\RecetteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/recette/supprimer']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'commentaire_add' => [['recetteId'], ['_controller' => 'App\\Controller\\CommentaireController::addCommentaire'], [], [['variable', '/', '[^/]++', 'recetteId', true], ['text', '/commentaire/add']], [], [], []],
    'commentaire_delete' => [['id'], ['_controller' => 'App\\Controller\\CommentaireController::deleteCommentaire'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commentaire/delete']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\IngredientController::nouvelleIngredient' => [[], ['_controller' => 'App\\Controller\\IngredientController::nouvelleIngredient'], [], [['text', '/creation/ingredient']], [], [], []],
    'App\Controller\IngredientController::show' => [['id'], ['_controller' => 'App\\Controller\\IngredientController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ingredient']], [], [], []],
    'App\Controller\IngredientController::listIngredients' => [[], ['_controller' => 'App\\Controller\\IngredientController::listIngredients'], [], [['text', '/ingredients']], [], [], []],
    'App\Controller\IngredientController::delete' => [['id'], ['_controller' => 'App\\Controller\\IngredientController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ingredient']], [], [], []],
    'App\Controller\RecetteController::create' => [[], ['_controller' => 'App\\Controller\\RecetteController::create'], [], [['text', '/recette/nouvelle']], [], [], []],
    'App\Controller\RecetteController::show' => [['id'], ['_controller' => 'App\\Controller\\RecetteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/recette']], [], [], []],
    'App\Controller\RecetteController::delete' => [['id'], ['_controller' => 'App\\Controller\\RecetteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/recette/supprimer']], [], [], []],
    'App\Controller\RecetteController::add' => [['recetteId'], ['_controller' => 'App\\Controller\\CommentaireController::addCommentaire'], [], [['variable', '/', '[^/]++', 'recetteId', true], ['text', '/commentaire/add']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
